[VASP]
xc = "PBE"
encut = 520
sigma = 0.05
ediff = 1e-6
ediffg = -0.05
algo = "all"
prec = "accurate"
ibrion = 2
isif = 3
ismear = 0
ispin = 2
nelmin = 8
nelm = 300
lmaxmix = 4
nsw = 999
lorbit = 12
ncore = 4
lcharg = true
lreal = "auto"
ldau = true
gamma = true
lwave = false
istart = 0
isym = 0
command = "mpirun vasp_std"
setups = "materialsproject"
symprec = 1e-6
kpts = [3,4,6]
